# Generated by Django 4.1.7 on 2023-02-15 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generating_csv", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Column",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Full_name", "Full Name"),
                            ("Job", "Job"),
                            ("Email", "Email"),
                            ("Phone_number", "Phone Number"),
                            ("Address", "Address"),
                            ("Integer", "Integer"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        unique=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("modified", models.TimeField(auto_now=True)),
                (
                    "columns",
                    models.ManyToManyField(
                        related_name="schemas", to="generating_csv.column"
                    ),
                ),
            ],
        ),
    ]
