# Generated by Django 4.1.7 on 2023-02-16 14:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("generating_csv", "0002_column_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="CSVData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified", models.TimeField(auto_now=True)),
                ("csv_file", models.URLField(max_length=255)),
                (
                    "rows",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="generating_csv.schema",
                    ),
                ),
            ],
        ),
    ]
