# Generated by Django 4.1.7 on 2023-02-18 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "generating_csv",
            "0005_column_end_num_column_stare_num_csvdata_status_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="column",
            old_name="stare_num",
            new_name="start_num",
        ),
    ]
