# Generated by Django 4.1.7 on 2023-02-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generating_csv", "0006_rename_stare_num_column_start_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schema",
            name="separator",
            field=models.CharField(
                choices=[(",", "Comma"), (":", "Colon"), (";", "Semicolon")],
                default=",",
                max_length=2,
            ),
        ),
    ]
